# NOTE: This file is automatically synchronized from Patina DevOps. Update the original file there
#       instead of the file in this repo.
#
# - Patina DevOps Repo: https://github.com/OpenDevicePartnership/patina-devops
# - File Sync Settings: https://github.com/OpenDevicePartnership/patina-devops/blob/main/.sync/Files.yml


[toolchain]
channel = "nightly-2026-04-11" # Last nightly build of 1.96.0-nightly
targets = ["x86_64-unknown-uefi", "aarch64-unknown-uefi", "x86_64-pc-windows-msvc", "aarch64-pc-windows-msvc", "x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu"]
components = ["rust-src", "clippy", "rustfmt", "rust-docs"]

# A custom section for CI pipelines to install tools
[tools]
cargo-deny = "^0.18"
cargo-geiger = "0.13.0"
cargo-llvm-cov = "0.6.18"
cargo-make = "0.37.21"
cargo-release = "0.25.12"
cargo-vet = "0.10.0"
mdbook = "0.4.52"
mdbook-admonish = "1.20.0"
mdbook-linkcheck = "0.7.7"
mdbook-mermaid = "0.16.2"

[msrv]
channel = "nightly-2025-06-20"   # branched-from date for rust-version = "1.89"
